export const COURSE_NAME_CHANGE = "COURSE_NAME_CHANGE";
export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const SECTION_NUMBER_CHANGE = "SECTION_NUMBER_CHANGE";
export const UPDATE_LECTURE_NAME = "UPDATE_LECTURE_NAME";

export const ADD_LECTURE_SLOT = "ADD_LECTURE_SLOT";
export const DELETE_LECTURE_SLOT = "DELETE_LECTURE_SLOT";
export const UPDATE_LECTURE_SLOT = "UPDATE_LECTURE_SLOT";
export const UPDATE_LECTURE_PROFESSOR = "UPDATE_LECTURE_PROFESSOR";

export const ADD_TUTORIAL_SLOT = "ADD_TUTORIAL_SLOT";
export const DELETE_TUTORIAL_SLOT = "DELETE_TUTORIAL_SLOT";
export const UPDATE_TUTORIAL_SLOT = "UPDATE_TUTORIAL_SLOT";

export const ADD_LAB_SLOT = "ADD_LAB_SLOT";
export const DELETE_LAB_SLOT = "DELETE_LAB_SLOT";
export const UPDATE_LAB_SLOT = "UPDATE_LAB_SLOT";

export const CHANGE_TUTORIAL_PREFIX = "CHANGE_TUTORIAL_PREFIX";
export const CHANGE_TUTORIAL_NAME = "CHANGE_TUTORIAL_NAME";
export const CHANGE_TUTORIAL_TA = "CHANGE_TUTORIAL_TA";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const ADD_TUTORIAL = "ADD_TUTORIAL";

export const CHANGE_LAB_PREFIX = "CHANGE_LAB_PREFIX";
export const CHANGE_LAB_NAME = "CHANGE_LAB_NAME";
export const CHANGE_LAB_TA = "CHANGE_LAB_TA";
export const DELETE_LAB = "DELETE_LAB";
export const ADD_LAB = "ADD_LAB";
