export const COURSE_NAME_CHANGE = "COURSE_NAME_CHANGE";
export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const SECTION_NUMBER_CHANGE = "SECTION_NUMBER_CHANGE";
export const UPDATE_LECTURE_NAME = "UPDATE_LECTURE_NAME";
export const UPDATE_LECTURE_SLOT = "UPDATE_LECTURE_SLOT";
